name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name : install
    - run: apt install osm2pgsql
    - name: Test
      run: echo "We are testing the pipeline schedule"
      


   
