name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: download dresden
      run: wget https://download.bbbike.org/osm/bbbike/Dresden/
    - name: install
      run: sudo apt install osm2pgsql
    - name: Test
      run: echo "We are testing the pipeline schedule"


      


   
